language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xlldnsz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xlldnsz/docker-react npm rum test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-udemy-section-7"
  env: "DockerReactUdemySection7-env"
  bucket_name: "elasticbeanstalk-eu-west-2-371232125960"
  bucket_path: "docker-react-udemy-section-7"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY